### ISSUE TITLE
OSError: No command "dot" found on host lab333tesla-Precision-7920-Tower. Please check that the corresponding package is installed.

### ISSUE THREAD

**Issue by 406354348** [kodiweera/difit#3]

**Comment by kodiweera** [comment]
what is  your operating system? If you are on a windows machine, please use the docker/singularity images. If you are on a linux system, install graphviz. For example,
 sudo apt-get install graphviz

**Comment by 406354348** [comment]
> 你的操作系统是什么？如果您在 Windows 机器上，请使用 docker/singularity 图像。如果您使用的是 linux 系统，请安装 graphviz。例如， sudo apt-get install graphviz

Sincerely thank you for your answer. I use Linux system. This problem has been solved
